package com.openclassrooms.realestatemanager.utils

const val SPINNER_SELECT = "--SELECT--"
const val STRING_EMPTY = ""
const val DOUBLE_00 = 0.0

const val TYPE_POI = "type"
const val IC_POI = "ic"

const val DOLLAR = "$"
const val EURO = "€"
const val CURRENCY_SHARED_PREFERENCES : String = "CURRENCY_SHARED_PREFERENCES"
const val CURRENCY_TAG : String = "CURRENCY_TAG"

const val BUNDLE_REFERENCE = "BUNDLE_REFERENCE"

const val ZOOM_STATIC_MAP = 15
const val SIZE_STATIC_MAP = "400x400"

const val ERROR_GEOCODER_ADDRESS = "ERROR_GEOCODER_ADDRESS"

const val LOCATION_PERMISSION_CODE = 101
const val CAMERA_PERMISSION_CODE = 102
const val READ_EXTERNAL_STORAGE_PERMISSION_CODE = 103
const val WRITE_EXTERNAL_STORAGE_PERMISSION_CODE = 104

const val IMAGE_PICK_GALLERY_CODE = 201
const val IMAGE_PICK_CAMERA_CODE = 202

const val NOTIFICATION_CHANNEL_ID = "NOTIFICATION_CHANNEL_ID"
const val NOTIFICATION_CHANNEL_NAME = "NOTIFICATION_CHANNEL_NAME"
const val NOTIFICATION_ID = 301


